print("Hello World!")
#print("Hello again")
#print("I like typing this.")
#print("This is fun.")
#print("Yay! Printing.")
#print("I'd much ather you 'not'.")
#print('I "said" do not touch this.')
#print("I did not touch anything at all")
